# Generated by Django 5.0.6 on 2024-07-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('Temperature', models.IntegerField()),
                ('Soil_moister', models.IntegerField()),
                ('Light_intensity', models.IntegerField()),
                ('Humidity', models.IntegerField(null=True)),
                ('air_Quality', models.IntegerField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='IMAGES')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
